### PR TITLE
fixes from initial installation

### PR DESCRIPTION
**Pull request by lgarrison**
A few fixes from my initial setup:
- Fix the littlemcmc `_sample_one_chain` import to `_sample` for the latest littlemcmc
- Add `chain=0, random_seed=random_seed` to match the import change
- Make some of the scripts executable
- Change the jitclass import to avoid numba warning

@bd-j I am very unsure if `chain=0` is the right value to use with the new `_sample` function.  Here is the source: https://github.com/eigenfoo/littlemcmc/blob/main/littlemcmc/sampling.py#L402

### CODE REVIEW

**Comment by bd-j** [comment]
I think chain=0 is fine with the default NDArray backend (other backends seem to be overridden anway) and seems to only be used for displaying the progressbar at the moment.  The sampling wrappers in littlemcmc look like they are getting rapidly more complex and aren't as stable as I'd hoped...

**Comment by lgarrison** [comment]
Yeah, that's too bad.  I guess these are "internal" functions we're dealing with, though.  Should we go ahead and merge these changes, or do you want to think about what to do about littlemcmc first?

**Comment by bd-j** [comment]
Is it working for you with these changes?  If so go ahead and merge.  I'm putting together install instructions and I think it's possible to specify a particular commit of littlemcmc.

**Comment by bd-j** [comment]
for reference I've been using f4053158863b5417780a1b on odyssey

**Comment by lgarrison** [comment]
Sounds good. We could also just pin to version 0.2.0, which was released 3 days ago, it looks like: https://github.com/eigenfoo/littlemcmc/releases/tag/v0.2.0

**Pull request merged**
